services:
  minio:
    command: server --console-address ":9001" /data1
    volumes:
      - minio-data-1:/data1
    networks:
      - dockerswarm_monitoring
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.minio == true
        preferences:
          - spread: "node.labels.minio"

  ingress:
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.minio == true
        preferences:
          - spread: "node.labels.minio"

volumes:
  minio-data-1:
    name: minio-data-1
    external: true

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true
