networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

volumes:
  minio-data:

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - dockerswarm_monitoring
    user: "${UID}:${GID}"
