target: all,ruler,overrides-exporter

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  grpc_server_max_recv_msg_size: 1048576000
  grpc_server_max_send_msg_size: 1048576000
  grpc_server_max_concurrent_streams: 10000

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      region: us-east-1
      bucket_name: mimir
      access_key_id: minioadmin
      secret_access_key: minioadmin
      insecure: true

blocks_storage:
  s3:
    bucket_name: mimir-blocks

ruler_storage:
  s3:
    bucket_name: mimir-ruler

compactor:
  sharding_ring:
    instance_addr: &instance_addr mimir-{{.Task.Slot}}
    kvstore: &default-ring-kvstore
      store: inmemory

  sharding_ring:
    instance_addr: *instance_addr
    kvstore: *default-ring-kvstore
    replication_factor: 3

distributor:
  pool:
    health_check_ingesters: true
  ha_tracker: # ha deduplication
    enable_ha_tracker: true
    kvstore: 
      <<: *default-ring-kvstore
      prefix: mimir/ha-tracker/
  ring:
    instance_addr: *instance_addr
    kvstore: *default-ring-kvstore

ingester:
  ring:
    instance_addr: *instance_addr
    kvstore: *default-ring-kvstore
    replication_factor: 3

query_scheduler:
  ring:
    instance_addr: *instance_addr
    kvstore: *default-ring-kvstore

ruler:
  ring:
    instance_addr: *instance_addr
    kvstore: 
      <<: *default-ring-kvstore
      prefix: mimir/rulers/

store_gateway:
  sharding_ring:
    instance_addr: *instance_addr
    kvstore: *default-ring-kvstore
    replication_factor: 3

overrides_exporter:
  ring:
    instance_addr: *instance_addr
    kvstore: *default-ring-kvstore

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000
    grpc_compression: snappy

limits:
  # ha deduplication
  accept_ha_samples: true

  # Enable TSDB block upload
  compactor_block_upload_enabled: true

  ingestion_rate: 100000
  ingestion_burst_size: 2000000
  max_label_name_length: 2048
  max_label_value_length: 4096
  max_label_names_per_series: 50
  max_global_series_per_user: 4500000

  # See https://grafana.com/docs/mimir/latest/configure/configure-metrics-storage-retention/
  # Delete from storage metrics data older than 3 months.
  compactor_blocks_retention_period: 1y
  # 
  # Or delete from specific tenant storage metrics data
  # tenant1:
  #   compactor_blocks_retention_period: 1y


# Disable the anonymous usage statistics reporting
# 
# If possible, we ask you to keep the usage reporting feature enabled and help us 
# understand more about how the open source community runs Mimir. 
# 
# In case you want to opt-out from anonymous usage statistics reporting,
# set the CLI flag -usage-stats.enabled=false or 
# change the following YAML configuration:
usage_stats:
  enabled: false
