spring:
  cloud:
    aws:
      sqs:
        region: "us-east-1"
        queue-name: "${QUEUE_NAME:gio-otel-lgtm-tutorial-queue}"
  jpa:
    open-in-view: false
    hibernate:

      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/"
    username: "${POSTGRES_USER:organovate}"
    password: "${POSTGRES_PASSWORD:organovate}"
  application:
    name: otel-lgtm-tutorial-worker
server:
  servlet:
    contextPath: "/api/v1"