version: "3.8"

x-common-envs: &common-envs
  POSTGRES_USER: otel-lgtm-tutorial
  POSTGRES_PASSWORD: otel-lgtm-tutorial
  POSTGRES_DB: otel-lgtm-tutorial
  DB_HOST: postgresql
  QUEUE_NAME: ${SQS_NAME}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

configs:
  grafana.ini:
    external: true

services:
  postgresql:
    image: postgres:17-alpine
    environment:
      <<: *common-envs

  api:
    image: "ghcr.io/giovalgas/otel-lgtm-tutorial-api:latest"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      <<: *common-envs

  worker:
    image: "ghcr.io/giovalgas/otel-lgtm-tutorial-worker:latest"
    depends_on:
      - postgres
    environment:
      <<: *common-envs

  frontend:
    image: "ghcr.io/giovalgas/otel-lgtm-tutorial-frontend:latest"
    ports:
      - "80:80"
