spring:
  cloud:
    aws:
      sqs:
        region: "us-east-1"
        queue-name: "${QUEUE_NAME:gio-otel-lgtm-tutorial-queue}"
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/otel-lgtm-tutorial"
    username: "${POSTGRES_USER:otel-lgtm-tutorial}"
    password: "${POSTGRES_PASSWORD:otel-lgtm-tutorial}"
  application:
    name: otel-lgtm-tutorial-api
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /docs

server:
  servlet:
    contextPath: "/api/v1"