x-deploy: &x-deploy-default
  replicas: 1
  placement:
    max_replicas_per_node: 1
    preferences:
      - spread: node.labels.grafana-loki
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-logging: &x-logging-default
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

volumes:
  loki:

configs:
  loki.yaml:
    external: true

services:
  loki:
    hostname: loki-{{.Task.Slot}}
    image: grafana/loki:latest
    command:
      - -config.expand-env=true
      - -config.file=/etc/loki/loki.yml
    networks:
      - dockerswarm_monitoring
    ports:
      - "3100:3100"
      - "9195:9095"
    volumes:
      - loki:/loki
    configs:
      - source: loki.yaml
        target: /etc/loki/loki.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy: *x-deploy-default
    logging: *x-logging-default
