multitenancy_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: minio:9000
      access_key: minioadmin
      secret_key: minioadmin
      insecure: true
    wal:
      path: /tempo-data/wal
    local:
      path: /tempo-data/blocks

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
  ring: &x-ring-config
    kvstore: &x-kvstore-config
      store: inmemory

metrics_generator:
  ring: 
    kvstore: *x-kvstore-config
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  traces_storage:
    path: /tempo-data/generator/traces
  storage:
    path: /tempo-data/generator/wal
    remote_write:
      - url: http://mimir:3100/api/v1/push
        send_exemplars: true
  processor:
    local_blocks:
      flush_to_storage: true

ingester:
  # Lifecycler is responsible for managing the lifecycle of entries in the ring.
  # For a complete list of config options check the lifecycler section under the ingester config at the following link -
  # https://cortexmetrics.io/docs/configuration/configuration-file/#ingester_config
  lifecycler:
    ring:
      # number of replicas of each span to make while pushing to the backend
      replication_factor: 1
      kvstore: *x-kvstore-config

compactor:
  ring: 
    kvstore: *x-kvstore-config

querier:
  frontend_worker:
    frontend_address: tempo:9095

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

overrides:
  defaults:
    metrics_generator:
      processors: ['service-graphs', 'span-metrics', 'local-blocks']

usage_report:
  reporting_enabled: false
