receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/mimir:
    endpoint: http://mimir:3100/otlp
    tls:
      insecure: true
  debug:

service:
  pipelines:
    metrics:
      receivers: [otlp, http]
      processors: [batch]
      exporters: [otlphttp/mimir]
    traces:
      receivers: [otlp, http]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]